import type {
  Job,
  Application,
  CandidateProfile,
  Notification,
  Company,
} from "@/types/candidate";

// ─── Companies ────────────────────────────────────────────────────────────────

export const MOCK_COMPANIES: Company[] = [
  {
    id: "c1",
    name: "Techlogix",
    logo: "TL",
    industry: "Information Technology",
    size: "1,000–5,000",
    location: "Lahore, Pakistan",
    website: "https://techlogix.com",
    description: "Techlogix is a leading IT services and solutions company delivering digital transformation to clients worldwide.",
  },
  {
    id: "c2",
    name: "Arbisoft",
    logo: "AR",
    industry: "Software Development",
    size: "500–1,000",
    location: "Lahore, Pakistan",
    website: "https://arbisoft.com",
    description: "Arbisoft builds world-class software solutions for startups and enterprises globally.",
  },
  {
    id: "c3",
    name: "Systems Limited",
    logo: "SL",
    industry: "Enterprise Software",
    size: "5,000–10,000",
    location: "Lahore, Pakistan",
    website: "https://systemsltd.com",
    description: "Systems Limited is Pakistan's premier IT company providing enterprise solutions and IT services.",
  },
  {
    id: "c4",
    name: "NetSol Technologies",
    logo: "NT",
    industry: "FinTech",
    size: "1,000–5,000",
    location: "Lahore, Pakistan",
    website: "https://netsoltech.com",
    description: "NetSol Technologies provides IT services and enterprise software solutions for the global leasing and finance industry.",
  },
  {
    id: "c5",
    name: "10Pearls",
    logo: "10",
    industry: "Digital Transformation",
    size: "1,000–5,000",
    location: "Karachi, Pakistan",
    website: "https://10pearls.com",
    description: "10Pearls is a digital innovation company helping organizations build next-generation digital products.",
  },
  {
    id: "c6",
    name: "Folio3",
    logo: "F3",
    industry: "AgTech & eCommerce",
    size: "500–1,000",
    location: "Karachi, Pakistan",
    website: "https://folio3.com",
    description: "Folio3 is a technology company focused on AgriTech, eCommerce, and enterprise software solutions.",
  },
];

// ─── Mock Jobs ────────────────────────────────────────────────────────────────

export const MOCK_JOBS: Job[] = [
  {
    id: "job1",
    title: "Senior React Developer",
    company: MOCK_COMPANIES[0],
    location: "Lahore, Pakistan",
    type: "HYBRID",
    experienceLevel: "SENIOR",
    salaryMin: 250000,
    salaryMax: 400000,
    salaryCurrency: "PKR",
    description: "We are looking for a Senior React Developer to join our growing engineering team. You will be responsible for building and maintaining high-quality web applications using React and modern JavaScript tooling.",
    responsibilities: [
      "Lead frontend architecture decisions for new features",
      "Collaborate with designers to implement pixel-perfect UIs",
      "Mentor junior developers and conduct code reviews",
      "Optimize application performance and ensure cross-browser compatibility",
      "Participate in Agile ceremonies and sprint planning",
    ],
    requirements: [
      "5+ years of experience with React.js",
      "Strong knowledge of TypeScript",
      "Experience with Next.js and SSR/SSG",
      "Familiarity with REST APIs and GraphQL",
      "Understanding of CI/CD pipelines",
    ],
    benefits: [
      "Competitive salary package",
      "Health insurance for employee and family",
      "Annual performance bonus",
      "Remote work flexibility (3 days/week)",
      "Learning & development budget",
    ],
    skills: ["React", "TypeScript", "Next.js", "GraphQL", "Tailwind CSS", "Git"],
    status: "PUBLISHED",
    openings: 2,
    postedAt: "2026-07-10T09:00:00Z",
    deadline: "2026-08-10T00:00:00Z",
    featured: true,
  },
  {
    id: "job2",
    title: "Node.js Backend Engineer",
    company: MOCK_COMPANIES[1],
    location: "Lahore, Pakistan",
    type: "FULL_TIME",
    experienceLevel: "MID",
    salaryMin: 180000,
    salaryMax: 280000,
    salaryCurrency: "PKR",
    description: "Join our backend team to build scalable APIs and microservices that power products used by millions globally.",
    responsibilities: [
      "Design and build RESTful APIs using Node.js and Express",
      "Manage PostgreSQL and MongoDB databases",
      "Implement authentication, caching, and security best practices",
      "Write unit and integration tests",
      "Collaborate with frontend teams on API contracts",
    ],
    requirements: [
      "3+ years with Node.js (Express/Fastify)",
      "Experience with PostgreSQL and MongoDB",
      "Knowledge of Redis for caching",
      "Familiarity with Docker and Kubernetes",
      "Good understanding of REST API design",
    ],
    benefits: [
      "Market-competitive salary",
      "Medical coverage",
      "Flexible working hours",
      "Team outings and events",
      "International project exposure",
    ],
    skills: ["Node.js", "Express", "PostgreSQL", "MongoDB", "Redis", "Docker"],
    status: "PUBLISHED",
    openings: 3,
    postedAt: "2026-07-11T10:00:00Z",
    deadline: "2026-08-15T00:00:00Z",
    featured: true,
  },
  {
    id: "job3",
    title: "UI/UX Designer",
    company: MOCK_COMPANIES[2],
    location: "Lahore, Pakistan",
    type: "FULL_TIME",
    experienceLevel: "MID",
    salaryMin: 150000,
    salaryMax: 220000,
    salaryCurrency: "PKR",
    description: "We're seeking a creative UI/UX Designer to craft beautiful, user-centered digital experiences for our enterprise products.",
    responsibilities: [
      "Create wireframes, prototypes, and high-fidelity mockups",
      "Conduct user research and usability testing",
      "Build and maintain the design system",
      "Collaborate closely with product managers and engineers",
      "Define and improve UX flows across products",
    ],
    requirements: [
      "3+ years of UI/UX design experience",
      "Proficiency in Figma",
      "Strong portfolio showcasing web/mobile work",
      "Understanding of design systems",
      "Knowledge of accessibility standards (WCAG)",
    ],
    benefits: [
      "Creative and supportive environment",
      "Health insurance",
      "Paid time off (21 days/year)",
      "Access to design conferences",
      "Career growth opportunities",
    ],
    skills: ["Figma", "Design Systems", "Prototyping", "User Research", "Adobe XD"],
    status: "PUBLISHED",
    openings: 1,
    postedAt: "2026-07-09T08:00:00Z",
    deadline: "2026-07-31T00:00:00Z",
    featured: false,
  },
  {
    id: "job4",
    title: "DevOps Engineer",
    company: MOCK_COMPANIES[3],
    location: "Remote",
    type: "REMOTE",
    experienceLevel: "SENIOR",
    salaryMin: 300000,
    salaryMax: 500000,
    salaryCurrency: "PKR",
    description: "Looking for an experienced DevOps Engineer to manage our cloud infrastructure and deployment pipelines.",
    responsibilities: [
      "Manage and optimize AWS/GCP cloud infrastructure",
      "Design and maintain CI/CD pipelines using Jenkins and GitHub Actions",
      "Implement monitoring, logging, and alerting systems",
      "Ensure high availability and disaster recovery",
      "Collaborate with development teams on release strategies",
    ],
    requirements: [
      "4+ years of DevOps experience",
      "Strong AWS or GCP expertise",
      "Proficiency with Kubernetes and Docker",
      "Experience with Terraform or Ansible",
      "Knowledge of monitoring tools (Datadog, Prometheus)",
    ],
    benefits: [
      "Fully remote work",
      "Top-tier compensation",
      "Medical and life insurance",
      "Annual AWS certification sponsorship",
      "Flexible PTO policy",
    ],
    skills: ["AWS", "Kubernetes", "Docker", "Terraform", "CI/CD", "Linux"],
    status: "PUBLISHED",
    openings: 2,
    postedAt: "2026-07-08T07:00:00Z",
    deadline: "2026-08-08T00:00:00Z",
    featured: true,
  },
  {
    id: "job5",
    title: "Data Scientist",
    company: MOCK_COMPANIES[4],
    location: "Karachi, Pakistan",
    type: "FULL_TIME",
    experienceLevel: "MID",
    salaryMin: 200000,
    salaryMax: 320000,
    salaryCurrency: "PKR",
    description: "Join our data team to build ML models and extract actionable insights from large datasets.",
    responsibilities: [
      "Build and deploy machine learning models",
      "Perform exploratory data analysis and statistical modeling",
      "Create dashboards and data visualizations",
      "Collaborate with product teams to translate business problems into data solutions",
      "Maintain and improve existing ML pipelines",
    ],
    requirements: [
      "3+ years of data science experience",
      "Proficiency in Python (pandas, scikit-learn, TensorFlow/PyTorch)",
      "Experience with SQL and large datasets",
      "Knowledge of statistical analysis and modeling",
      "Familiarity with cloud ML platforms (AWS SageMaker, GCP AI Platform)",
    ],
    benefits: [
      "Competitive salary",
      "Health and dental coverage",
      "Conference and training budget",
      "Stock options",
      "Flexible work hours",
    ],
    skills: ["Python", "Machine Learning", "TensorFlow", "SQL", "Pandas", "Tableau"],
    status: "PUBLISHED",
    openings: 1,
    postedAt: "2026-07-07T09:00:00Z",
    deadline: "2026-08-07T00:00:00Z",
    featured: false,
  },
  {
    id: "job6",
    title: "Full Stack Developer (.NET)",
    company: MOCK_COMPANIES[2],
    location: "Lahore, Pakistan",
    type: "FULL_TIME",
    experienceLevel: "MID",
    salaryMin: 160000,
    salaryMax: 250000,
    salaryCurrency: "PKR",
    description: "Join our enterprise solutions team to build robust .NET-based applications for global clients.",
    responsibilities: [
      "Develop full-stack features using .NET 8 and Angular",
      "Write clean, maintainable code following SOLID principles",
      "Participate in requirements gathering and solution design",
      "Support QA teams with bug fixes and testing",
      "Maintain technical documentation",
    ],
    requirements: [
      "3+ years with .NET (C#, ASP.NET Core)",
      "Experience with Angular or React",
      "SQL Server database design",
      "Knowledge of Entity Framework",
      "Understanding of Azure cloud services",
    ],
    benefits: [
      "EOBI and social security",
      "Medical allowance",
      "Transport facility",
      "Performance-based increments",
      "Study leave support",
    ],
    skills: [".NET", "C#", "Angular", "SQL Server", "Azure", "Entity Framework"],
    status: "PUBLISHED",
    openings: 4,
    postedAt: "2026-07-06T08:30:00Z",
    deadline: "2026-08-06T00:00:00Z",
    featured: false,
  },
  {
    id: "job7",
    title: "Mobile Developer (Flutter)",
    company: MOCK_COMPANIES[5],
    location: "Karachi, Pakistan",
    type: "HYBRID",
    experienceLevel: "MID",
    salaryMin: 170000,
    salaryMax: 260000,
    salaryCurrency: "PKR",
    description: "Build cutting-edge mobile applications for iOS and Android using Flutter for our growing product portfolio.",
    responsibilities: [
      "Develop cross-platform mobile apps using Flutter/Dart",
      "Integrate REST APIs and Firebase services",
      "Ensure high performance and responsiveness",
      "Publish and maintain apps on App Store and Play Store",
      "Write automated tests for mobile components",
    ],
    requirements: [
      "2+ years with Flutter/Dart",
      "Experience with state management (Bloc, Riverpod)",
      "Firebase integration experience",
      "Understanding of mobile UI/UX principles",
      "Knowledge of app store deployment",
    ],
    benefits: [
      "Competitive salary",
      "Health insurance",
      "Flexible hours",
      "Gym membership",
      "Team retreats",
    ],
    skills: ["Flutter", "Dart", "Firebase", "Bloc", "iOS", "Android"],
    status: "PUBLISHED",
    openings: 2,
    postedAt: "2026-07-05T10:00:00Z",
    deadline: "2026-08-05T00:00:00Z",
    featured: false,
  },
  {
    id: "job8",
    title: "AI/ML Engineer",
    company: MOCK_COMPANIES[0],
    location: "Remote",
    type: "REMOTE",
    experienceLevel: "SENIOR",
    salaryMin: 350000,
    salaryMax: 600000,
    salaryCurrency: "PKR",
    description: "Lead AI/ML engineering efforts to build intelligent features into our enterprise platform.",
    responsibilities: [
      "Design and implement AI-powered features",
      "Build and maintain LLM pipelines and RAG systems",
      "Optimize model inference for production",
      "Collaborate with product teams on AI roadmap",
      "Stay current with latest AI research",
    ],
    requirements: [
      "4+ years of ML engineering experience",
      "Deep knowledge of LLMs (OpenAI, Gemini, LLaMA)",
      "Experience with vector databases (Pinecone, Weaviate)",
      "Strong Python skills",
      "MLOps and model deployment experience",
    ],
    benefits: [
      "Market-leading salary",
      "Fully remote",
      "Research time allocation",
      "Conference speaking opportunities",
      "Annual performance bonus",
    ],
    skills: ["Python", "LLMs", "RAG", "PyTorch", "Vector DB", "MLOps"],
    status: "PUBLISHED",
    openings: 1,
    postedAt: "2026-07-12T09:00:00Z",
    deadline: "2026-08-12T00:00:00Z",
    featured: true,
  },
  {
    id: "job9",
    title: "QA Engineer",
    company: MOCK_COMPANIES[1],
    location: "Lahore, Pakistan",
    type: "FULL_TIME",
    experienceLevel: "MID",
    salaryMin: 120000,
    salaryMax: 180000,
    salaryCurrency: "PKR",
    description: "Ensure the quality of our software products through thorough manual and automated testing.",
    responsibilities: [
      "Create and execute test plans and test cases",
      "Develop automated tests using Selenium/Cypress",
      "Report and track bugs in Jira",
      "Participate in sprint reviews and retrospectives",
      "Perform regression, integration, and performance testing",
    ],
    requirements: [
      "2+ years of QA experience",
      "Familiarity with Selenium or Cypress",
      "Knowledge of API testing (Postman)",
      "Experience with Jira or similar tools",
      "ISTQB certification is a plus",
    ],
    benefits: [
      "Medical insurance",
      "Flexible working hours",
      "Quarterly bonuses",
      "Learning subscriptions (Udemy, Coursera)",
      "Team events",
    ],
    skills: ["Selenium", "Cypress", "Postman", "Jira", "Test Automation", "Agile"],
    status: "PUBLISHED",
    openings: 2,
    postedAt: "2026-07-04T08:00:00Z",
    deadline: "2026-08-04T00:00:00Z",
    featured: false,
  },
  {
    id: "job10",
    title: "Product Manager",
    company: MOCK_COMPANIES[4],
    location: "Karachi, Pakistan",
    type: "FULL_TIME",
    experienceLevel: "SENIOR",
    salaryMin: 280000,
    salaryMax: 420000,
    salaryCurrency: "PKR",
    description: "Drive product strategy and execution for our B2B SaaS platform with a strong focus on user outcomes.",
    responsibilities: [
      "Define and communicate the product vision and roadmap",
      "Gather requirements from stakeholders and customers",
      "Write detailed PRDs and user stories",
      "Work with engineering and design teams to deliver features",
      "Analyze product metrics and drive improvements",
    ],
    requirements: [
      "5+ years of product management experience",
      "Experience with B2B SaaS products",
      "Strong analytical and data-driven mindset",
      "Excellent communication and stakeholder management skills",
      "Technical background is a plus",
    ],
    benefits: [
      "Executive compensation package",
      "Health and life insurance",
      "ESOPs",
      "International travel",
      "Remote-first culture",
    ],
    skills: ["Product Strategy", "Roadmapping", "Jira", "Analytics", "Agile", "PRDs"],
    status: "PUBLISHED",
    openings: 1,
    postedAt: "2026-07-03T09:00:00Z",
    deadline: "2026-08-03T00:00:00Z",
    featured: false,
  },
  {
    id: "job11",
    title: "Frontend Developer (Vue.js)",
    company: MOCK_COMPANIES[3],
    location: "Remote",
    type: "REMOTE",
    experienceLevel: "MID",
    salaryMin: 160000,
    salaryMax: 250000,
    salaryCurrency: "PKR",
    description: "Build interactive and responsive frontend applications using Vue.js 3 for our FinTech platform.",
    responsibilities: [
      "Develop Vue.js components and composables",
      "Integrate with backend APIs",
      "Maintain code quality through reviews",
      "Collaborate with UX designers",
      "Write unit tests with Vitest",
    ],
    requirements: [
      "3+ years with Vue.js (preferably Vue 3)",
      "TypeScript experience",
      "Pinia or Vuex state management",
      "Familiarity with Nuxt.js",
      "CSS/SCSS proficiency",
    ],
    benefits: [
      "Remote work",
      "Flexible hours",
      "Medical allowance",
      "Annual leave encashment",
      "Team meetups",
    ],
    skills: ["Vue.js", "TypeScript", "Nuxt.js", "Pinia", "Vitest", "SCSS"],
    status: "PUBLISHED",
    openings: 2,
    postedAt: "2026-07-02T10:00:00Z",
    deadline: "2026-08-02T00:00:00Z",
    featured: false,
  },
  {
    id: "job12",
    title: "Business Analyst",
    company: MOCK_COMPANIES[2],
    location: "Lahore, Pakistan",
    type: "FULL_TIME",
    experienceLevel: "MID",
    salaryMin: 130000,
    salaryMax: 200000,
    salaryCurrency: "PKR",
    description: "Bridge the gap between business stakeholders and technology teams by analyzing processes and defining requirements.",
    responsibilities: [
      "Conduct requirements gathering sessions",
      "Create functional specifications and BRDs",
      "Model AS-IS and TO-BE business processes",
      "Facilitate workshops and stakeholder meetings",
      "Support UAT and training activities",
    ],
    requirements: [
      "3+ years as a Business Analyst",
      "Experience with BPMN/UML modeling",
      "Proficiency in Confluence and Jira",
      "Strong communication skills",
      "Exposure to software development lifecycle",
    ],
    benefits: [
      "EOBI benefits",
      "Medical coverage",
      "Provident fund",
      "Annual bonus",
      "Career development programs",
    ],
    skills: ["Requirements Analysis", "BPMN", "Jira", "Confluence", "SQL", "Agile"],
    status: "PUBLISHED",
    openings: 2,
    postedAt: "2026-07-01T09:00:00Z",
    deadline: "2026-07-31T00:00:00Z",
    featured: false,
  },
];

// ─── Mock Applications ─────────────────────────────────────────────────────────

export const MOCK_APPLICATIONS: Application[] = [
  {
    id: "app1",
    job: {
      id: "job1",
      title: "Senior React Developer",
      company: MOCK_COMPANIES[0],
      location: "Lahore, Pakistan",
      type: "HYBRID",
    },
    status: "SHORTLISTED",
    appliedAt: "2026-07-11T10:00:00Z",
    updatedAt: "2026-07-12T15:00:00Z",
    coverLetter: "I am excited to apply for this position...",
  },
  {
    id: "app2",
    job: {
      id: "job3",
      title: "UI/UX Designer",
      company: MOCK_COMPANIES[2],
      location: "Lahore, Pakistan",
      type: "FULL_TIME",
    },
    status: "IN_REVIEW",
    appliedAt: "2026-07-10T09:30:00Z",
    updatedAt: "2026-07-11T11:00:00Z",
  },
  {
    id: "app3",
    job: {
      id: "job5",
      title: "Data Scientist",
      company: MOCK_COMPANIES[4],
      location: "Karachi, Pakistan",
      type: "FULL_TIME",
    },
    status: "REJECTED",
    appliedAt: "2026-07-08T08:00:00Z",
    updatedAt: "2026-07-10T14:00:00Z",
  },
  {
    id: "app4",
    job: {
      id: "job8",
      title: "AI/ML Engineer",
      company: MOCK_COMPANIES[0],
      location: "Remote",
      type: "REMOTE",
    },
    status: "APPLIED",
    appliedAt: "2026-07-13T09:00:00Z",
    updatedAt: "2026-07-13T09:00:00Z",
  },
  {
    id: "app5",
    job: {
      id: "job4",
      title: "DevOps Engineer",
      company: MOCK_COMPANIES[3],
      location: "Remote",
      type: "REMOTE",
    },
    status: "INTERVIEWED",
    appliedAt: "2026-07-05T10:00:00Z",
    updatedAt: "2026-07-12T16:00:00Z",
  },
];

// ─── Mock Saved Jobs ──────────────────────────────────────────────────────────

export const INITIAL_SAVED_JOB_IDS = ["job2", "job4", "job7", "job10"];

// ─── Mock Candidate Profile ───────────────────────────────────────────────────

export const MOCK_CANDIDATE_PROFILE: CandidateProfile = {
  id: "cand1",
  name: "Ahmad Hassan",
  email: "ahmad.hassan@email.com",
  phone: "+92 300 1234567",
  location: "Lahore, Pakistan",
  title: "Full Stack Developer",
  bio: "Passionate full-stack developer with 4+ years of experience building scalable web applications. I love solving complex problems and delivering clean, maintainable code.",
  avatar: "AH",
  skills: ["React", "Node.js", "TypeScript", "PostgreSQL", "Docker", "AWS", "Next.js", "Python"],
  resumeUrl: null,
  workExperience: [
    {
      id: "we1",
      company: "Arbisoft",
      role: "Software Engineer",
      startDate: "2023-01",
      endDate: null,
      current: true,
      description: "Building scalable backend services and React frontend applications for global clients.",
    },
    {
      id: "we2",
      company: "Freelance",
      role: "Full Stack Developer",
      startDate: "2021-06",
      endDate: "2022-12",
      current: false,
      description: "Developed multiple web applications for clients across e-commerce and healthcare sectors.",
    },
  ],
  education: [
    {
      id: "edu1",
      institution: "University of Engineering and Technology, Lahore",
      degree: "Bachelor of Science",
      field: "Computer Science",
      startYear: 2017,
      endYear: 2021,
      current: false,
    },
  ],
  linkedinUrl: "https://linkedin.com/in/ahmadhassan",
  portfolioUrl: "https://ahmadhassan.dev",
};

// ─── Mock Notifications ───────────────────────────────────────────────────────

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: "n1",
    type: "APPLICATION_UPDATE",
    title: "Your application was shortlisted! 🎉",
    message: "Congratulations! Techlogix has moved your application for 'Senior React Developer' to the shortlist.",
    read: false,
    createdAt: "2026-07-12T15:00:00Z",
    jobTitle: "Senior React Developer",
    companyName: "Techlogix",
  },
  {
    id: "n2",
    type: "INTERVIEW",
    title: "Interview Scheduled",
    message: "NetSol Technologies has scheduled an interview for 'DevOps Engineer' on July 15, 2026 at 11:00 AM.",
    read: false,
    createdAt: "2026-07-12T10:00:00Z",
    jobTitle: "DevOps Engineer",
    companyName: "NetSol Technologies",
  },
  {
    id: "n3",
    type: "JOB_MATCH",
    title: "New job match for you",
    message: "A new job matching your profile has been posted: 'AI/ML Engineer' at Techlogix.",
    read: false,
    createdAt: "2026-07-12T09:00:00Z",
    jobTitle: "AI/ML Engineer",
    companyName: "Techlogix",
  },
  {
    id: "n4",
    type: "APPLICATION_UPDATE",
    title: "Application under review",
    message: "Systems Limited is reviewing your application for 'UI/UX Designer'.",
    read: true,
    createdAt: "2026-07-11T11:00:00Z",
    jobTitle: "UI/UX Designer",
    companyName: "Systems Limited",
  },
  {
    id: "n5",
    type: "APPLICATION_UPDATE",
    title: "Application not selected",
    message: "We're sorry, 10Pearls has decided not to move forward with your application for 'Data Scientist'.",
    read: true,
    createdAt: "2026-07-10T14:00:00Z",
    jobTitle: "Data Scientist",
    companyName: "10Pearls",
  },
  {
    id: "n6",
    type: "GENERAL",
    title: "Profile completion reminder",
    message: "Complete your profile to increase your chances of getting noticed by top employers. Add your resume and work experience.",
    read: true,
    createdAt: "2026-07-09T09:00:00Z",
  },
];

// ─── Helper: format salary ────────────────────────────────────────────────────

export function formatSalary(min: number, max: number, currency: string): string {
  const fmt = (n: number) => {
    if (n >= 100000) return `${(n / 1000).toFixed(0)}K`;
    return n.toLocaleString();
  };
  return `${currency} ${fmt(min)} – ${fmt(max)}`;
}

// ─── Helper: time ago ─────────────────────────────────────────────────────────

export function timeAgo(dateStr: string): string {
  const date = new Date(dateStr);
  const now = new Date();
  const diffMs = now.getTime() - date.getTime();
  const diffDays = Math.floor(diffMs / (1000 * 60 * 60 * 24));

  if (diffDays === 0) return "Today";
  if (diffDays === 1) return "1 day ago";
  if (diffDays < 7) return `${diffDays} days ago`;
  if (diffDays < 30) return `${Math.floor(diffDays / 7)} week${Math.floor(diffDays / 7) > 1 ? "s" : ""} ago`;
  return `${Math.floor(diffDays / 30)} month${Math.floor(diffDays / 30) > 1 ? "s" : ""} ago`;
}
